### ISSUE TITLE
Don't rely on a third party service for per-commit testing

### ISSUE THREAD

**Issue by soup-bowl** [soup-bowl/wp-simple-smtp#64]
Each commit is currently being tested against **mailtrap**. While this works well enough for the main repository builds, PRs made from external repositories (as experienced by Kebbet) will fail each build, as they do not have these settings in their own repository secrets. Since the docker-compose instance this project comes with contains an SMTP mocking service, it would make much more sense to adjust the build process to run against this instead. This will mean PRs and forks will be able to run per-commit and PR tests just fine.

EDIT: Correction - The build process does **not** currently use docker-compose.

**Comment by soup-bowl** [comment]
Been trying this outside of this repository. I've tried the following approaches separately:
```
- name: Sendria SMTP server in GitHub Actions
        uses: upgundecha/start-sendria-github-action@v1.0.0
        with:
          smtp-port: 1025
```
```
    services:
      smtp_mock:
        image: mailhog/mailhog:latest
        ports:
        - 1025:1025
        - 8025:8025
```
```
      - name: Spin-up Mock SMTP
        run: >
          docker run -d
          -p 1025:1025
          -p 8025:8025
          --hostname smtp_mock
          --name smtp_mock
          mailhog/mailhog:latest
```
(8025 exposure was me checking the SMTP service wasn't failing itself and CURLing the response).

All three fail with the same issue of being unable to resolve the hostname.
```
2021-11-01 22:17:36	Connection: opening to localhost:1025, timeout=300, options=array()
2021-11-01 22:17:36	Connection failed. Error #2: stream_socket_client(): Unable to connect to localhost:1025 (Address not available) [/app/vendor/phpmailer/phpmailer/src/SMTP.php line 388]
2021-11-01 22:17:36	SMTP ERROR: Failed to connect to server: Address not available (99)
2021-11-01 22:17:36	SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
```
Instructions on using GitHub Actions suggest that exposing the ports in the build chain are supposed to be accessible in the localhost, so I'm unclear why this leads to failure.

Still pressing at it, just noting my investigations.

**Comment by evrpress** [comment]
Hey, any progress on this? I'm looking a way to test mails via Github actions but cannot get this working either.

**Comment by soup-bowl** [comment]
> Hey, any progress on this? I'm looking a way to test mails via Github actions but cannot get this working either.

**Afraid not.** I'm working on an OpenSimulator project so I haven't been able to dedicate the time to this, but I tried ~2 weeks ago and wasn't able to get an outcome. I really don't understand why, as I've tried opening a mock SMTP server on both the Docker instance, docker instance w/public port & a [dedicated GitHub Action](https://github.com/marketplace/actions/sendria-smtp-server-in-github-actions), all three fail reporting the instance isn't available on the network... Strange.

On the same note, I'm not giving up on this, so keep an eye on this if you continue to be stuck on this, as once I've solved it I'll be sure to write up how.

**Comment by evrpress** [comment]
Thanks for the quick response!

I've tried this

```
     - name: Start Sendira
        uses: upgundecha/start-sendria-github-action@v1.0.0
        with:
          smtp-port: 1025
          http-port: 1080
          sendira-version: '2.2.1'

      - name: Test
         run: |
          curl -LI http://127.0.0.1:1080
```

but there's no connection to this address (same with `localhost:1080`)

I also cannot use `sendria --help` in my Test step as it returns "not found"

**Comment by evrpress** [comment]
I've asked [a question](https://stackoverflow.com/questions/71020182/run-sendria-mailtrap-in-a-github-workflow-to-test-mail-delivery-in-a-wordpress) on SO if you are interested

**Comment by soup-bowl** [comment]
Thanks for this - I'll keep an eye on it! This will greatly assist if someone is able to help shed light on it, so I'll reference the SO thread in the changelog once it comes to a potential resolution.

**Comment by soup-bowl** [comment]
Going to restructure the unit tests to mock and remove the physical SMTP reliance. I'm keen to keep a physical SMTP test in the Action chain so if any further possible resolutions appear I'd like to hear them, but for now I'll restructure it so that the main repo recieves full tests, but all PRs and branches recieve mock tests.

**Comment by evrpress** [comment]
Nice, got it working on a repo to test a WordPress plugin. Here's the part of the job:

```
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [7.2]
        wordpress-version: [latest]
    services:
      sendria:
        image: msztolcman/sendria:v2.2.2.0
        ports:
          - 1080:1080
          - 1025:1025

    steps:
      - name: Set up MySqL
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "5.7"
          root-password: "root"

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          tools: composer, cs2pr

      - name: Test sendria connection
        run: curl -LI localhost:1080

      - name: Checkout repository
        uses: actions/checkout@v1
  ```
